
spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.24.9.53:3306/wechat-dev?characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 50
      # 获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
  redis:
    port: 6379
    host: localhost
mybatis:
  type-aliases-package: com.swpu.uchain.openexperiment.domain
  mapper-locations: classpath:mappers/*.xml
###security###
jwt:
  secret: swpu-uchain
  expiration: 1296000
#redis
redis:
  host: localhost
  port: 6379
  timeout: 10
  poolMaxTotal: 1000
  poolMaxIdle: 500
  poolMaxWait: 500
##page##
page:
  count:
    announcement: 10
    project: 5
    check-user: 10
    check-project: 7
    manage-user: 7
    manage-role: 7
#server:
#  tomcat:
#    max-http-header-size: 10240


