server:
  port: 8085
#应用维护
#启动shutdown模块
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown
      base-path: /uchain
  server:
    port: ${server.port}
    address: 127.0.0.1
spring:
  datasource:
    username: root
    password: 13458264160
