server:
  port: 8085
#应用维护
#启动shutdown模块
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown
      base-path: /uchain
  server:
    port: ${server.port}
    address: 127.0.0.1
spring:
  datasource:
    #注意如果数据库中时间是否和真实时间一致,不一致的话需要对serverTimezone进行配置
    url: jdbc:mysql://localhost:3306/wechat-prod?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Qq771.com
