server:
  port: 8080
spring:
  datasource:
    username: root
    password: Qq771.com

  servlet:
    multipart:
      enabled: true
      # 设置文件大小限制  10MB
      max-file-size: 102400000
      # 设置总上传数据总大小 30MB
      max-request-size: 307200000
