server:
  port: 8080
spring:
  datasource:
    username: root
    #注意如果数据库中时间是否和真实时间一致,不一致的话需要对serverTimezone进行配置
    url: jdbc:mysql://localhost:3306/wechat-dev?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    password: Qq771.com
  servlet:
    multipart:
      enabled: true
      # 设置文件大小限制  10MB
      max-file-size: 102400000
      # 设置总上传数据总大小 30MB
      max-request-size: 307200000
tmpFilePath: "/Users/mac/Downloads/tmp/"